import { nanoid } from "../types/nanoid";
import type { Block, BlockType } from "../types/blocks";

export function createDefaultBlock(type: BlockType): Block {
  const id = nanoid();
  const defaults: Record<BlockType, object> = {
    heading: { text: "Heading", level: 2, align: "left", fontWeight: "bold" },
    text: { text: "Add your text here. Click to edit.", align: "left" },
    button: { label: "Click here", href: "#", target: "_self", variant: "primary", align: "left", size: "md" },
    image: { src: "", alt: "Image", width: 100, align: "center", objectFit: "cover" },
    container: { paddingTop: 32, paddingBottom: 32, paddingLeft: 16, paddingRight: 16, children: [] },
    "two-column": { gap: 24, leftWidth: 50, leftChildren: [], rightChildren: [], stackOnMobile: true, paddingTop: 32, paddingBottom: 32 },
    "three-column": { gap: 24, col1Children: [], col2Children: [], col3Children: [], stackOnMobile: true, paddingTop: 32, paddingBottom: 32 },
    gallery: { images: [], columns: 3, gap: 16, showCaptions: false },
    "contact-form": {
      fields: [
        { id: nanoid(), label: "Name", type: "text", required: true },
        { id: nanoid(), label: "Email", type: "email", required: true },
        { id: nanoid(), label: "Message", type: "textarea", required: true },
      ],
      submitLabel: "Send Message",
      successMessage: "Thank you! We'll be in touch soon.",
      submitMode: "formspree",
      formspreeEndpoint: "",
      paddingTop: 48,
      paddingBottom: 48,
    },
    footer: {
      companyName: "Your Company",
      copyrightText: `© ${new Date().getFullYear()} Your Company. All rights reserved.`,
      links: [{ id: nanoid(), label: "Privacy", href: "#" }],
      backgroundColor: "#1e293b",
      textColor: "#94a3b8",
      align: "center",
      paddingTop: 32,
      paddingBottom: 32,
    },
    navigation: {
      logoText: "My Site",
      logoType: "text",
      links: [
        { id: nanoid(), label: "Home", href: "index.html" },
        { id: nanoid(), label: "About", href: "about.html" },
        { id: nanoid(), label: "Contact", href: "contact.html" },
      ],
      sticky: false,
      backgroundColor: "#ffffff",
      textColor: "#1e293b",
      showMobileMenu: true,
    },
    "slide-banner": {
      slides: [
        {
          id: nanoid(),
          imageSrc: "",
          imageAlt: "Slide 1",
          title: "Welcome to our site",
          subtitle: "We create amazing experiences",
          ctaLabel: "Learn more",
          ctaHref: "#",
          overlayColor: "rgba(0,0,0,0.35)",
          titleColor: "#ffffff",
          subtitleColor: "#f1f5f9",
        },
        {
          id: nanoid(),
          imageSrc: "",
          imageAlt: "Slide 2",
          title: "Our Services",
          subtitle: "Discover what we offer",
          ctaLabel: "See more",
          ctaHref: "#",
          overlayColor: "rgba(0,0,0,0.35)",
          titleColor: "#ffffff",
          subtitleColor: "#f1f5f9",
        },
      ],
      height: 480,
      autoplay: true,
      autoplayInterval: 4000,
      showArrows: true,
      showIndicators: true,
      objectFit: "cover",
    },
    divider: {
      variant: "rule",
      height: 1,
      color: "#e2e8f0",
      lineStyle: "solid",
      width: 100,
      marginTop: 24,
      marginBottom: 24,
    },
    video: {
      url: "",
      videoType: "youtube",
      aspectRatio: "16/9",
      controls: true,
      autoplay: false,
      muted: false,
      loop: false,
      align: "center",
      width: 100,
    },
    hero: {
      heading: "Build Something Amazing",
      subheading: "A beautiful, fast, and reliable platform to help you create stunning websites.",
      ctaLabel: "Get Started",
      ctaHref: "#",
      ctaVariant: "primary",
      ctaSecondaryLabel: "Learn More",
      ctaSecondaryHref: "#",
      backgroundImage: "",
      backgroundColor: "#1e293b",
      overlayColor: "rgba(0,0,0,0.5)",
      headingColor: "#ffffff",
      subheadingColor: "#cbd5e1",
      textAlign: "center",
      paddingTop: 96,
      paddingBottom: 96,
      minHeight: 500,
    },
    testimonial: {
      items: [
        {
          id: nanoid(),
          quote: "This product changed everything for us. Highly recommend!",
          authorName: "Jane Doe",
          authorTitle: "CEO at Acme Corp",
          authorAvatar: "",
          rating: 5,
        },
        {
          id: nanoid(),
          quote: "Incredibly easy to use and the results speak for themselves.",
          authorName: "John Smith",
          authorTitle: "Founder at TechStart",
          authorAvatar: "",
          rating: 5,
        },
      ],
      columns: 2,
      cardColor: "#ffffff",
      quoteColor: "#1e293b",
      authorColor: "#64748b",
      showRating: true,
      paddingTop: 48,
      paddingBottom: 48,
    },
    "pricing-table": {
      plans: [
        {
          id: nanoid(),
          name: "Starter",
          price: "Free",
          period: "",
          description: "Perfect for individuals getting started.",
          features: [
            { id: nanoid(), text: "5 projects", included: true },
            { id: nanoid(), text: "10 GB storage", included: true },
            { id: nanoid(), text: "Email support", included: false },
          ],
          ctaLabel: "Get Started",
          ctaHref: "#",
          highlighted: false,
          highlightColor: "#2563eb",
        },
        {
          id: nanoid(),
          name: "Pro",
          price: "$19",
          period: "/month",
          description: "Ideal for growing teams and businesses.",
          features: [
            { id: nanoid(), text: "Unlimited projects", included: true },
            { id: nanoid(), text: "100 GB storage", included: true },
            { id: nanoid(), text: "Priority support", included: true },
          ],
          ctaLabel: "Start Free Trial",
          ctaHref: "#",
          highlighted: true,
          highlightColor: "#2563eb",
        },
      ],
      paddingTop: 64,
      paddingBottom: 64,
    },
    icon: {
      iconName: "star",
      size: 48,
      color: "#2563eb",
      align: "center",
      label: "",
      labelColor: "#1e293b",
      href: "",
    },
    map: {
      embedUrl: "https://www.openstreetmap.org/export/embed.html?bbox=-0.1277%2C51.5074%2C-0.1077%2C51.5174&layer=mapnik",
      height: 400,
      align: "center",
      width: 100,
    },
    "four-column": {
      gap: 24,
      col1Children: [],
      col2Children: [],
      col3Children: [],
      col4Children: [],
      stackOnMobile: true,
      paddingTop: 32,
      paddingBottom: 32,
    },
    "asymmetric-column": {
      gap: 32,
      leftWidth: 33,
      leftChildren: [],
      rightChildren: [],
      stackOnMobile: true,
      paddingTop: 32,
      paddingBottom: 32,
      leftVerticalAlign: "top",
      rightVerticalAlign: "top",
    },
    "vertical-stack": {
      gap: 16,
      align: "stretch",
      showDivider: false,
      dividerColor: "#e2e8f0",
      paddingTop: 32,
      paddingBottom: 32,
      paddingLeft: 0,
      paddingRight: 0,
      children: [],
    },
    "masonry-grid": {
      columns: 3,
      gap: 16,
      paddingTop: 32,
      paddingBottom: 32,
      items: [[], [], []],
    },
    "product-card": {
      name: "Product Name",
      description: "Short product description goes here.",
      price: "€ 29.90",
      imageSrc: "",
      imageAlt: "Product image",
      badge: "",
      ctaLabel: "Buy Now",
      ctaHref: "#",
      ctaTarget: "_self",
      paddingTop: 16,
      paddingBottom: 16,
      borderRadius: 12,
      shadow: true,
      outlined: false,
      backgroundColor: "#ffffff",
    },
    "product-grid": {
      items: [
        { id: nanoid(), name: "Product 1", description: "Description", price: "€ 29.90", imageSrc: "", imageAlt: "Product 1", badge: "New", ctaLabel: "Buy Now", ctaHref: "#", ctaTarget: "_self" },
        { id: nanoid(), name: "Product 2", description: "Description", price: "€ 49.90", imageSrc: "", imageAlt: "Product 2", badge: "", ctaLabel: "Buy Now", ctaHref: "#", ctaTarget: "_self" },
        { id: nanoid(), name: "Product 3", description: "Description", price: "€ 19.90", imageSrc: "", imageAlt: "Product 3", badge: "Sale", ctaLabel: "Buy Now", ctaHref: "#", ctaTarget: "_self" },
      ],
      columns: 3,
      gap: 24,
      paddingTop: 48,
      paddingBottom: 48,
      cardStyle: "shadowed",
      borderRadius: 12,
    },
    "product-detail": {
      name: "Product Name",
      description: "This is a detailed product description. Explain what makes your product special and why customers should buy it.",
      price: "€ 99.90",
      imageSrc: "",
      imageAlt: "Product image",
      badge: "",
      ctaLabel: "Add to Cart",
      ctaHref: "#",
      ctaTarget: "_self",
      features: ["Feature one", "Feature two", "Feature three"],
      layout: "image-left",
      galleryImages: [],
      backgroundColor: "#ffffff",
      paddingTop: 64,
      paddingBottom: 64,
      accentColor: "#f59e0b",
    },
    "cart-button": {
      position: "fixed-bottom-right",
      backgroundColor: "#2563eb",
      iconColor: "#ffffff",
      label: "",
    },
    faq: {
      headingText: "Frequently Asked Questions",
      items: [
        { id: nanoid(), question: "What is your return policy?", answer: "We offer a 30-day money-back guarantee on all orders.", open: false },
        { id: nanoid(), question: "How long does shipping take?", answer: "Standard shipping takes 3–5 business days.", open: false },
        { id: nanoid(), question: "Do you offer customer support?", answer: "Yes! Our support team is available 24/7 via email and live chat.", open: false },
      ],
      accentColor: "#2563eb",
      backgroundColor: "#ffffff",
      textColor: "#1e293b",
      paddingTop: 64,
      paddingBottom: 64,
    },
    embed: {
      url: "",
      height: 400,
      title: "Embedded content",
      allowFullscreen: true,
      align: "center",
    },
    "social-share": {
      url: "",
      title: "",
      platforms: ["twitter", "facebook", "linkedin", "whatsapp"],
      align: "center",
      buttonStyle: "both",
      iconColor: "#ffffff",
      backgroundColor: "#2563eb",
    },
    "cookie-banner": {
      message: "We use cookies to improve your experience on our website. By continuing to browse, you agree to our cookie policy.",
      acceptLabel: "Accept All",
      declineLabel: "Decline",
      backgroundColor: "#1e293b",
      textColor: "#f1f5f9",
      buttonColor: "#2563eb",
      storageKey: "sp_cookie_consent",
    },
    countdown: {
      targetDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      heading: "Limited Time Offer",
      expiredText: "Offer has expired",
      accentColor: "#2563eb",
      textColor: "#1e293b",
      backgroundColor: "#f8fafc",
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: true,
      align: "center",
      paddingTop: 48,
      paddingBottom: 48,
    },
    timeline: {
      items: [
        { id: nanoid(), date: "2020", title: "Company Founded", content: "We started with a simple idea and a small team.", icon: "🚀" },
        { id: nanoid(), date: "2021", title: "First Product Launch", content: "Launched our flagship product to market success.", icon: "🎉" },
        { id: nanoid(), date: "2022", title: "Growing Team", content: "Expanded to 50 employees across 3 countries.", icon: "🌍" },
        { id: nanoid(), date: "2023", title: "Award Winning", content: "Recognized as one of the top startups of the year.", icon: "🏆" },
      ],
      accentColor: "#2563eb",
      dateColor: "#64748b",
      textColor: "#1e293b",
      lineColor: "#e2e8f0",
      align: "left",
      paddingTop: 64,
      paddingBottom: 64,
    },
  };
  return { id, type, props: defaults[type] } as Block;
}
